### ISSUE TITLE
POST calls received as GET

### ISSUE THREAD

**Issue by kemcake** [kubeless/kubeless-ui#14]
For an unknown reason, when sending a `POST` call to a function (`/api/v1/proxy/namespaces/default/services/foo`), the function receive a `GET` request

Here are some facts:
- Sending a curl POST request works fine.
- I thought it was due to the `cors-proxy` used to fix cors in dev, but a curl request through the cors-proxy works fine.
- Sending a POST request to create the function works fine.
- Sending a POST request in the app, through the cors-proxy, to a sample api server (https://httpbin.org/post) works fine.

I'm thinking about a problem with headers on the kubernetes api server, if someone has any idea..?

**Comment by sebgoa** [comment]
which version of k8s and which version of kubeless are you using ?

**Comment by sebgoa** [comment]
I am going to wait for Tuna to tell me things are stable before testing things again.

**Comment by kemcake** [comment]
Kubernetes: `v1.6.0` (server)
Kubeless: `v0.0.11`

**Comment by kemcake** [comment]
Fixed with #16, removing the `cors-anywhere` proxy
