### ISSUE TITLE
CORS not running in Docker image

### ISSUE THREAD

**Issue by sebgoa** [kubeless/kubeless-ui#18]
@jbianquetti-nami the UI runs on port 3000 but there is a CORS proxy running on port 3001.

I am wondering if in the Docker image, the CORS proxy process actually starts properly, preventing the UI to load functions when running inside a cluster. #17

**Comment by kemcake** [comment]
The cors proxy was only running in dev mode, but this should be fixed with #16 that include a manual proxy backend, running also in production.

**Comment by sebgoa** [comment]
yes, it is working now

thanks
