### ISSUE TITLE
Install kubeless from UI

### ISSUE THREAD

**Issue by kemcake** [kubeless/kubeless-ui#19]
I'm wondering if it could be a good idea to allow the installation of kubeless/kubeless-controller directly from the UI

Just opening the discussion, to see what it involves 🙌

**Comment by sebgoa** [comment]
it is a bit of a chicken and egg issue.

I just committed a manifest to deploy the UI in the kubeless repo.
https://github.com/kubeless/kubeless/pull/154

But yes, we could start the UI `npm start` and have a button that checks it there is a reachable controller, if not, then propose to launch it (which would just be the creation of a manifest).

**Comment by sebgoa** [comment]
I am going to close this. we are going to have a chart to deploy Kubeless, and it will include the UI.
