### ISSUE TITLE
use next.js instead of davezuko/react-redux-starter-kit which is deprecated

### ISSUE THREAD

**Issue by danutc** [kubeless/kubeless-ui#27]
I suggest you have a look to https://github.com/zeit/next.js/

IMO it is very easy to use and it is a good replacement for

https://github.com/davezuko/react-redux-starter-kit
and
https://github.com/facebookincubator/create-react-app

**Comment by kemcake** [comment]
I saw that `react-redux-starter-kit` was deprecated, but this was just to use the basic stack provided, it's not a framework and as long as we keep the dependencies up to date it's doesn't matter :). I agree that `next.js` looks interesting tho, but this would require some work just to update the current stack

**Comment by danutc** [comment]
next.js is a good / easy replacement for create-react-app; here is a short blog that explains:
https://medium.com/@diamondgfx/nextjs-lessons-learned-part-1-a5a8d442450f
https://medium.com/@diamondgfx/nextjs-lessons-learned-part-2-f1781237cf5c
https://medium.com/@diamondgfx/nextjs-lessons-learned-part-3-be3aeefd9be0

**Comment by sebgoa** [comment]
@danutc thanks for the links, we will happily accept any PR to change things around.
