### ISSUE TITLE
Load python dependencies from Kubeless UI

### ISSUE THREAD

**Issue by zdlgrj** [kubeless/kubeless-ui#28]
Migrated from https://github.com/kubeless/kubeless/issues/229.

Feature: Have a option to load python dependencies from Kubeless UI

**Comment by kemcake** [comment]
Definitely could be useful, I'll give it a try to see how we can achieve that 👍

**Comment by kemcake** [comment]
Ok we can simply go with something like this:

![screenshot 2017-07-28 12 10 34](https://user-images.githubusercontent.com/4311124/28732733-e1debaae-738d-11e7-8274-d446910742eb.png)

PR coming soon 💪

**Comment by zdlgrj** [comment]
@kemcake Looks great! we can also have a comma or space separated input for multiple deps.

**Comment by kemcake** [comment]
Hm I think the intended format is line breaks, but maybe we can add something that automatically replace commas and spaces with linebreaks... Or having something like a tag list input could be better...

**Comment by kemcake** [comment]
So this feature is implemented in #32 🎉
