### ISSUE TITLE
Unable to connect to Minikube via Kubeless UI

### ISSUE THREAD

**Issue by arjunrao87** [kubeless/kubeless-ui#30]
I am running the kubeless UI and it comes up just fine. However, I am unable to create any new functions or see existing functions through the UI. I am running behind a proxy so I am wondering if that has anything to do with it. My minikube cluster IP is 192.168.99.100. The cluster IP on the Kubeless UI is like so 

![screen shot 2017-10-12 at 11 09 53 am](https://user-images.githubusercontent.com/2516336/31503529-e8de0c7e-af3d-11e7-81ca-b29d71940fdb.png)
I try to create the function and while the function modal pops up it doesnt actually create anything. 
![screen shot 2017-10-12 at 11 10 47 am](https://user-images.githubusercontent.com/2516336/31503593-183fa98c-af3e-11e7-9197-5576be6ba49e.png)
![screen shot 2017-10-12 at 11 10 56 am](https://user-images.githubusercontent.com/2516336/31503595-19d5e234-af3e-11e7-8aa8-0b0fc6776534.png)

When I look at the ui pod logs I see this 
```
yarn run v0.24.4
$ better-npm-run start 
running better-npm-run in /app
Executing script: start
 to be executed: node bin/server 
Thu, 12 Oct 2017 14:59:59 GMT app:config:project Creating default configuration.
Thu, 12 Oct 2017 14:59:59 GMT app:config:project Looking for environment overrides for NODE_ENV "production".
Thu, 12 Oct 2017 14:59:59 GMT app:config:project Found overrides, applying to default configuration.
Thu, 12 Oct 2017 15:00:01 GMT app:config:webpack Creating configuration.
Thu, 12 Oct 2017 15:00:01 GMT app:config:webpack Enabling plugins for production (OccurenceOrder, Dedupe & UglifyJS).
Thu, 12 Oct 2017 15:00:01 GMT app:config:webpack Applying ExtractTextPlugin to CSS loaders.
Thu, 12 Oct 2017 15:00:01 GMT app:bin:server 
  💻  Server is now running on port 3000
Thu, 12 Oct 2017 15:00:28 GMT app:server Error: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the API version in the data () does not match the expected API version (k8s.io/v1)","reason":"BadRequest","code":400}
 Thu, 12 Oct 2017 15:01:03 GMT app:server Error: request to http://192.168.99.100:8080/api/v1/pods failed, reason: connect ECONNREFUSED 192.168.99.100:8080
Thu, 12 Oct 2017 15:01:03 GMT app:server Error: request to http://192.168.99.100:8080/apis/k8s.io/v1/functions failed, reason: connect ECONNREFUSED 192.168.99.100:8080
Thu, 12 Oct 2017 15:01:09 GMT app:server Error: request to http://192.168.99.100:8080/apis/k8s.io/v1/namespaces/default/functions failed, reason: connect ECONNREFUSED 192.168.99.100:8080
Thu, 12 Oct 2017 15:02:27 GMT app:server Error: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the API version in the data () does not match the expected API version (k8s.io/v1)","reason":"BadRequest","code":400}
 Thu, 12 Oct 2017 15:10:45 GMT app:server Error: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the API version in the data () does not match the expected API version (k8s.io/v1)","reason":"BadRequest","code":400}
 Thu, 12 Oct 2017 15:14:46 GMT app:server Error: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the API version in the data () does not match the expected API version (k8s.io/v1)","reason":"BadRequest","code":400}
```
There seem to be 2 errors here 
- Refusal to connect ( could be a proxy issue but right now i have no means of passing a no_proxy env var  to the UI deployment )
- API version mismatch ( I am not sure what this error means )

What do you think is the problem here?

**Comment by sebgoa** [comment]
How are you deploying the UI ?

The easiest way is to run the UI as a k8s deployment and a svc:

```
kubectl create -f https://raw.githubusercontent.com/kubeless/kubeless/master/manifests/ui/ui-deployment.yaml
kubectl create -f https://raw.githubusercontent.com/kubeless/kubeless/master/manifests/ui/ui-svc.yaml
```

the manifests are in the kubeless/kubeless repo: https://github.com/kubeless/kubeless/tree/master/manifests/ui

**Comment by sebgoa** [comment]
and checking the readme  in this repo, it is clearly undocumented...sorry about that

**Comment by arjunrao87** [comment]
Yup using the same commands to deploy the UI. No worries. Once I figure out this problem, I will contribute to the documentation!

**Comment by sebgoa** [comment]
Are you using RBAC in your cluster ?

**Comment by sebgoa** [comment]
looks like there is a connection refused on 192.168.99.100 , but the UI code running inside a Pod should really be talking to localhost:8080 - which goes to the kubernetes API server thanks to a sidecar proxy-.

so I am not sure why it is talking to 192.168.99.100 :(

**Comment by arjunrao87** [comment]
@sebgoa  I am not using RBAC. I am confused by this error too 
```
Tue, 17 Oct 2017 20:30:48 GMT app:server Error: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the API version in the data () does not match the expected API version (k8s.io/v1)","reason":"BadRequest","code":400}
```
Is this a thirdpartyresources API mismatch? Do I need to update minikube for this version of kubeless or something?

**Comment by andresmgot** [comment]
It seem that indeed you have an old version of the Kubeless UI. @sebgoa has just pushed a manifest that you can use to deploy the UI. First remove the current svc/deployments that you may have running, then just executing:

```
kubectl create -f https://raw.githubusercontent.com/kubeless/kubeless-ui/master/k8s.yaml
```

That will expose a node port in minikube so you can retrieve it:

```
kubectl get svc ui -n kubeless
NAME      CLUSTER-IP   EXTERNAL-IP   PORT(S)          AGE
ui        10.0.0.151   <pending>     3000:31172/TCP   12m
```

and access the UI at `$(minikube ip):31172`

**Comment by arjunrao87** [comment]
Bingo that worked. Looks like the previous manifest was pointing an incorrect ui version. Thanks @andresmgot
