### ISSUE TITLE
Want flexible root URL

### ISSUE THREAD

**Issue by anguslees** [kubeless/kubeless-ui#41]
When deploying kubeless-ui alongside other services, it would be really useful if I could put kubeless-ui somewhere other than `/` on a dedicated hostname.  Ideally kubeless-ui would use relative URLs for other kubeless-ui assets (stylesheets, javascript, etc), or failing that use a URL path prefix configurable via docker env/args.

**Comment by sebgoa** [comment]
@kemcake could you take a look at this ?

**Comment by kemcake** [comment]
Ok should be fixed with https://github.com/kubeless/kubeless-ui/commit/33bf78546ba5ecdd8f2ca591281f5759940679d5 - updating the compiler_public_path of webpack config

**Comment by prydonius** [comment]
This is now fully fixed in #44
