### ISSUE TITLE
new code updated on kubeless-ui  doesn't take effect

### ISSUE THREAD

**Issue by chz8494** [kubeless/kubeless-ui#60]
got this bug when try to change existing code on kubeless-ui.
For example:
1. create a new python2.7 function on kubeless-ui.
2. it will automatically generate a simple "hello world" code.
3. now if I change this code, to make it say "hello 123", and save it, then click on "run function", it will still show result "hello world".

Although I can see function got changed if I do "kubectl get function -o yaml", the result has no changes at all.
the result only changes when I manually delete function pod, which will trigger a recreation of that pod. I think this is due to recreation of a function pod reloads function scripts.

suggestions: automatically kill old pod if user changes and saves a script on kubeless-ui

**Comment by andresmgot** [comment]
Indeed, the checksum is not properly updated so it doesn't trigger the rolling update.

**Comment by andresmgot** [comment]
Should be fixed with #61 . Let us know if you find any other issue!
