### ISSUE TITLE
adding deps doesn't work

### ISSUE THREAD

**Issue by chz8494** [kubeless/kubeless-ui#62]
create function on UI with deps has no effect. function's dep field shows empty.

I can modify function to add dep(kubectl apply -f ) after creation though, and then deps shows on UI.

**Comment by andresmgot** [comment]
_checking_ Thanks again for reporting

**Comment by andresmgot** [comment]
I've tried that and I can successfully add dependencies to a function. Which language are you working with? Note that in the case of Python you need to press "enter" before deploying the function to parse the dependencies. Could that be your issue?

**Comment by chz8494** [comment]
you are right! that's it, hitting "enter" is the key.
